config/routes.rb
Blog::Application.routes.draw do
  get "students/certificat"
  get "students/pay"


   get "account_to_semesters/pay"
   post "account_to_semesters/pay"

  post "pay_category_to_semesters/new"

  post "pay_category_to_semesters/new1"
  get "pay_category_to_semesters/new1"

  post "pay_category_to_semesters/kalkul"
  get "pay_category_to_semesters/kalkul"

  post "pay_category_to_semesters/stip1"
  get "pay_category_to_semesters/stip1"

  post "pay_category_to_semesters/stip2"
  get "pay_category_to_semesters/stip2"

  get "pay_to_month_students/pay_metod"
  post "pay_to_month_students/pay_metod"


  resources :operations

  resources :students do
    resources :certificats
    resources :student_groups
  end
  resources :groups
  resources :faculties do
    resources :account_to_semesters
  end
  resources :orders


  resources :student_groups
  resources :account_to_semesters

  resources :pay_category_to_semesters
  resources :pay_to_month_students
  resources :certificats
  resources :posts do
    resources :comments
  end
 root "welcome#index"

  get "static_pages/home"

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  #root  'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

  get "new_bases/group"
  get "new_bases/student"
  get "new_bases/student_group"
  post "new_bases/create_student_group"
  post "new_bases/create_student"
  post "new_bases/create_group"
end

app/models/student.rb
class Student < ActiveRecord::Base

  has_many :pay_to_month_students
  has_many :certificats
  has_many :student_groups
  has_many :groups, through: :student_groups
  
  validates_presence_of :firstname, :surname,
  message: " поле должнобыть заполнено" 
  
  # validates_format_of :firstname, :surname, :secondname,
  #   :allow_nil=>true,:allow_blank=>true,
  #   with:  /\A[А-ЯA-Z]/,
  #   message: "ФИО должны начинатся с большой буквы"





end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :signed_in_user
  before_action :correct_faculty, only: [:show, :certificat, :pay, :edit, :update]
  before_action :no_admin, only: [:index, :new, :create, :destroy]

  def new
    @student = Student.new
  end
 
  def create
    @student = Student.new(student_params)

    if @student.save
      #redirect_to @student
      redirect_to :controller => 'student_groups', :action => 'index'
    else
      render 'new'
    end
  end
  
  def show
    #@student = Student.includes(:certificats,:groups,{:student_groups=>{:group=>:faculty}},:pay_to_month_students).find(params[:id])
  end

  def certificat
    #@student = Student.includes(:certificats).find(params[:student_id])
  end

  def pay
    #@student = Student.includes(:pay_to_month_students).find(params[:id])
  end

  def index
    @students = Student.all
    @students &= @students.find_all{|x| x.surname.include? params[:surname]} unless params[:surname].nil? or  params[:surname].empty?
    @students &= @students.find_all{|x| x.firstname.include? params[:firstname]} unless params[:firstname].nil? or  params[:firstname].empty?
    @students &= @students.find_all{|x| x.secondname.include? params[:secondname]} unless params[:secondname].nil? or  params[:secondname].empty?
    @students &= @students.find_all{|x| x.text.include? params[:text]} unless params[:text].nil? or  params[:text].empty?
  end

  def update
    #@student = Student.find(params[:id])
    if @student.update(student_params)
      redirect_to @student
    else
      render 'edit'
    end
  end
  
  def destroy
    @student = Student.find(params[:id])
    @student.destroy
    redirect_to students_path
  end

  def edit
    #@student = Student.find(params[:id])
  end

private
  def student_params
    params.require(:student).permit(:firstname,:surname, :surname_dp, :surname_rp,:secondname, :text)
  end

  def correct_faculty
    @student = Student.includes(:certificats,:groups,{:student_groups=>{:group=>:faculty}},:pay_to_month_students).find(params[:id])
    redirect_to help_url, notice: 'Доступ запрещен' unless current_user.faculty.name == 'all' || @student.student_groups.map{|x| x.group}.map{|x| x.faculty_id}.include?(current_user.faculty_id)
  end

  def no_admin
    redirect_to help_url, notice: 'Доступ запрещен' unless current_user.faculty.name == 'all'
  end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/certificat.html.erb
<%= link_to "<<< Вернуться", :back, class: "btn btn-large btn-primary enabled"%>

<h1> <%= @student.surname %> <%=@student.firstname %> <%= @student.secondname %></h1>

<p>
  <strong>Примечание:</strong>
  <%= @student.text %>
</p>


<h2>Справки</h2>
<table class="table table-striped">
  <tr>

    <th>№ справки</th>
    <th>Кем выдана</th>
    <th>Дата выдачи </th>
    <th>Начало <br>выплат </th>
    <th>Конец <br>выплат </th>
    <th>Дата окончания </th>
    <% if can? :delete,Certificat %>
        <th>Редактирование</th>
    <%end%>
  </tr>

  <% @student.certificats.sort_by { |s| s.date_finish}.reverse.each do |certificat| %>
      <tr align=center>
        <td><%= link_to " #{certificat.number}", edit_certificat_path(certificat) %></td>
        <td><%= certificat.who %></td>
        <td><%= certificat.when.strftime("%d.%m.%Y") %></td>
        <td><% if certificat.month_start<10%>0<%end%><%= certificat.month_start %>.<%= certificat.year_start %></td>
        <td><% if certificat.month_finish<10%>0<%end%><%= certificat.month_finish %>.<%= certificat.year_finish %></td>
        <td><%= certificat.date_finish.strftime("%d.%m.%Y") %></td>
        <% if can? :delete,Certificat and (Date.today-certificat.date_finish).to_i<180%>
            <td><i class="icon-search"></i><%= link_to 'Удалить', certificat_path(certificat), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
  <% end %>
</table>


<% if  can? :create, Certificat  %>
    <h2>Добавить справку:</h2>
    <%= form_for([@student, @student.certificats.build]) do |f| %>
        <% @student.certificats.map(&:errors).each do |e|%>
            <%if e.messages.any?%>
                <div id="error_explanation" class="error_explanation">
                  <h2>Сообщение: сохранение не удалось из-за <%= e.count %> ошибки:</h2>
                  <ul>
                    <% e.full_messages.each do |msg| %>
                        <li><%= msg %></li>
                    <% end %>
                  </ul>
                </div>
            <% end %>
        <% end %>

        <% if @student.errors.any? %>
            <div id="error_explanation" class="error_explanation">
              <h2>Сообщение: сохранение не удалось из-за <%= @student.errors.count %> ошибки:</h2>
              <ul>
                <% @student.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
        <% end %>

        <p>
          № справки:<br>
          <%= f.text_field :number %>
        </p>

        <p>
          Кем выдана:<br>
          <%= f.text_field :who %>
        </p>
          Дата выдачи:<br>
        <div class="row">
          <div class='col-sm-2'>
            <div class="form-group">
              <div class='input-group date' id='datetimepicker1'>
                <%= f.text_field :when, class: "form-control" %>
                <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span>
                    </span>
              </div>
            </div>
          </div>
          <script type="text/javascript">
              $(function () {
                  $('#datetimepicker1').datetimepicker({
                      pickTime: false,
                      language: 'ru'
                  });
              });
          </script>
        </div>
        <p>
          Начало выплат:<br>
          <%#= f.text_field :month_start %>
          <%= select_month(Date.today, field_name: 'month_start', :prefix => 'certificat')%>
          <%#=f.text_field :year_start %>
          <%= select_year(Date.today, field_name: 'year_start', :prefix => 'certificat')%>
        </p>

        <p>
          Конец выплат:<br>
          <%#= f.text_field :month_finish %>
          <%= select_month(Date.today.next_year, field_name: 'month_finish', :prefix => 'certificat')%>
          <%#=f.text_field :year_finish %>
          <%= select_year(Date.today.next_year, field_name: 'year_finish', :prefix => 'certificat')%>
        </p>

          Дествительно до:<br>
        <div class="row">
          <div class='col-sm-2'>
            <div class="form-group">
              <div class='input-group date' id='datetimepicker2'>
                <%= f.text_field :date_finish, class: "form-control" %>
                <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span>
                    </span>
              </div>
            </div>
          </div>
          <script type="text/javascript">
              $(function () {
                  $('#datetimepicker2').datetimepicker({
                      pickTime: false,
                      language: 'ru'
                  });
              });
          </script>
        </div>

        <div class="form-actions">
          <button type="submit" class="btn btn-success">Сохранить</button>
          <button type="reset" class="btn">Отменить</button>
        </div>
    <% end %>
<% end %>

app/views/students/edit.html.erb
<h2>Изменение параметров студента</h2>

<%= form_for :student, url: student_path(@student), method: :patch do |f| %>
    <% if @student.errors.any? %>
        <div id="error_explanation" class="error_explanation">
            <h2>Сообщение: сохранение не удалось из-за <%= @student.errors.count %> ошибки:</h2>
            <ul>
                <% @student.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    <p>
        Фамилия:<br>
        <%= f.text_field :surname %>
    </p>
    <p>
        Имя:<br>
        <%= f.text_field :firstname %>
    </p>
    <p>
        Отчество:<br>
        <%= f.text_field :secondname %>
    </p>
    <p>
        Коментарии:<br>
        <%= f.text_area :text %>
    </p>
    <p>
        Фамилия в родительном падеже:<br>
        <%= f.text_field :surname_rp, placeholder: 'Кого?' %>
    </p>
    <p>
        Фамилия в дательном падеже:<br>
        <%= f.text_field :surname_dp, placeholder: 'Кому?' %>
    </p>

    <div class="form-actions">
        <button type="submit" class="btn btn-success">Сохранить</button>
        <button type="reset" class="btn">Отменить</button>
    </div>
<% end %>

app/views/students/index.html.erb
<div class="well  well-small">
    <%= form_tag("/students", method: "get") do |f| %>
        <div class="row">
            <div class="col-md-4">
                Фамилия:<br>
                <%= text_field_tag(:surname,  params[:surname])%><br>

                Имя:<br>
                <%= text_field_tag(:firstname, params[:firstname]) %><br>

                Отчество:  <br>
                <%= text_field_tag(:secondname, params[:secondname]) %><br>

                Комментарии:<br>
                <%= text_field_tag(:text, params[:text])%>
            </div>
            <div class="col-md-4" >
                <button class="btn btn-large btn-info" type="submit" >Поиск</button>
                <button class="btn btn-large" type="reset"  >Очистить</button>
            </div>
        </div>
    <% end %>
</div >


<h1>Студенты</h1>


  <p>  
  <a href="/students/new" class="btn btn-large btn-success enabled">Новый студент</a>
  </p>

<table class="table table-striped">
  <tr>
     <th>Фамилия</th>
     <th>Имя</th>
     <th>Отчество</th>
     <th>Прочее</th>
	 <th>Редактирование</th>
     
  </tr>

	<% @students.sort_by {|s| s.surname}.each do |student| %>
			<tr>
				<td><%= student.surname %></td>
				<td><%= student.firstname %></td>
				<td><%= student.secondname %></td>
				<td><%= student.text %></td>

			 
			  <td><%= link_to 'Show', student %>
              	  <%= link_to 'Edit', edit_student_path(student) %>
				  <%= link_to 'Destroy', student_path(student),
							method: :delete, data: { confirm: 'Are you sure?' } %></td>
              <td><%=  link_to "Справки", controller: "students", action: "certificat", student_id: student.id %></td>
			</tr>
	<% end %>

</table>

app/views/students/new.html.erb
<%= link_to "<<< Вернуться", :back, class: "btn btn-large btn-primary enabled"%>
<h2>Создание нового студента</h2>
<%= form_for :student , url: students_path do |f| %>
  <% if @student.errors.any? %>
  <div id="error_explanation" class="error_explanation">
    <h2>Сообщение: сохранение не удалось из-за <%= @student.errors.count %> ошибки:</h2>
    <ul>
    <% @student.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

<p>
    Фамилия:<br>
    <%= f.text_field :surname %>
  </p>
  <p>
    Имя:<br>
    <%= f.text_field :firstname %>
  </p>
 <p>
  Отчество:<br>
  <%= f.text_field :secondname %>
</p>
  <p>
    Коментарии:<br>
    <%= f.text_area :text %>
  </p>

       <div class="form-actions">
    <button type="submit" class="btn btn-success">Сохранить</button>
    <button type="reset" class="btn">Отменить</button>
    </div>
 
<% end %>

app/views/students/pay.html.erb
<h1> <%= @student.surname %> <%=@student.firstname %> <%= @student.secondname %></h1>

<p>
    <strong>Примечание:</strong>
    <%= @student.text %>
</p>


<h2>Выплаты по месяцам</h2>
<table class="table table-striped">
    <tr>
        <th>Дата выплат</th>
        <th>Соц. </th>
        <th>Акад. </th>
        <th>уч. д-ть</th>
        <th>общ. д-ть</th>
        <th>нид</th>
        <th>культ. д-ть</th>
        <th>спорт. д-ть</th>
        <th>Тип</th>
        <th>Доплата</th>
        <th>Всего</th>
        <th></th>
    </tr>

    <% @student.pay_to_month_students.sort_by {|x| [x.year, x.month]}.reverse.each do |pay_to_month_student| %>
        <tr>
            <td><% if pay_to_month_student.month<10%>0<%end%><%= pay_to_month_student.month %>.<%= pay_to_month_student.year %></td>
            <td><%= pay_to_month_student.social %></td>
            <td><%= pay_to_month_student.academic %></td>
            <td><%= pay_to_month_student.study %></td>
            <td><%= pay_to_month_student.public %></td>
            <td><%= pay_to_month_student.scientific %></td>
            <td><%= pay_to_month_student.cultural %></td>
            <td><%= pay_to_month_student.sports %></td>

            <td><%=PayToMonthStudent::TYPE_PAY_SHORT[pay_to_month_student.type_pay]%></td>
            <td><%= pay_to_month_student.surcharge %></td>
            <td><%=pay_to_month_student.social.to_i+pay_to_month_student.academic.to_i+pay_to_month_student.study.to_i+pay_to_month_student.public.to_i+pay_to_month_student.scientific.to_i+pay_to_month_student.cultural.to_i+pay_to_month_student.sports.to_i+pay_to_month_student.surcharge.to_i %></td>
            <% if can? :manager,PayToMonthStudent %>
                <td bgcolor="#c9302c">
                    <%= link_to 'Show', pay_to_month_student %>
                    <%= link_to 'Edit', edit_pay_to_month_student_path(pay_to_month_student) %>
                    <%= link_to 'Destroy', pay_to_month_student_path(pay_to_month_student), method: :delete, data: { confirm: 'Are you sure?' } %>
                </td>
            <% end %>
        </tr>
    <% end %>
</table>

app/views/students/show.html.erb
<h1> <%= @student.surname %> <%=@student.firstname %> <%= @student.secondname %></h1>

<p>
  <strong>Примечание:</strong>
  <%= @student.text %>
</p>

<%= link_to 'Изменить параметры студента', edit_student_path(@student), class: "btn btn-success"   %>

<h2>Справки</h2>
<table class="table table-striped">
    <tr>

        <th>№ справки</th>
        <th>Кем выдан</th>
        <th>Дата выдачи </th>
        <th>Начало выплат </th>
        <th>Конец выплат </th>
        <th>Дата окончания </th>
    </tr>

    <% @student.certificats.sort_by {|x| x.date_finish}.reverse.each do |certificat| %>
        <tr>

        <td><%= link_to " #{certificat.number}", edit_certificat_path(certificat) %></td>
        <td><%= certificat.who %></td>
        <td><%=l certificat.when %></td>
        <td><% if certificat.month_start<10%>0<%end%><%= certificat.month_start %>.<%= certificat.year_start %></td>
        <td><% if certificat.month_finish<10%>0<%end%><%= certificat.month_finish %>.<%= certificat.year_finish %></td>
        <td><%=l certificat.date_finish %></td>

        <% if can? :manager, :all %>
            <td bgcolor="#c9302c">
                <%= link_to 'Show', certificat %>
                <%= link_to 'Edit', edit_certificat_path(certificat) %>
                <%= link_to 'Destroy', certificat_path(certificat), method: :delete, data: { confirm: 'Вы уверены, что хотите удалить?' } %>
            </td>
        <% end %>
        </tr>
    <% end %>
</table>



<h2>Группы</h2>
<table class="table table-striped">
    <tr>
        <th>Название</th>
        <th>Курс</th>
        <th>Семестр    </th>
        <th>Учебный год</th>
        <th>Факультет</th>

    </tr>


    <% @student.groups.sort_by{|x| [x.year, x.kurs, x.semester, x.name] }.reverse.each do |group| %>
        <tr>
            <td><%=link_to "#{group.name}", group %></td>
            <td><%= group.kurs %></td>
            <td><%= group.semester %></td>
            <td><%= group.year %></td>
            <td><%= group.faculty.short_name %></td>

            <% if can? :manager, :all%>
                <td bgcolor="#c9302c">
                    <%= link_to 'Show', group %>
                    <%= link_to 'Edit', edit_group_path(group) %>
                    <%= link_to 'Destroy', group_path(group), method: :delete, data: { confirm: 'Вы уверены, что хотите удалить?' } %>
                </td>
            <% end %>
        </tr>
    <% end %>
</table>

<h2>Выплаты по месяцам</h2>
<table class="table table-striped">
    <tr>
        <th>Дата выплат</th>
        <th>Соц. </th>
        <th>Акад. </th>
        <th>уч. д-ть</th>
        <th>общ. д-ть</th>
        <th>нид</th>
        <th>культ. д-ть</th>
        <th>спорт. д-ть</th>
        <th>Тип</th>
        <th>Доплата</th>
        <th>Всего</th>

    </tr>

    <% @student.pay_to_month_students.sort_by { |q| [q.year,q.month]}.reverse.each do |pay_to_month_student| %>
        <tr>
            <td><%= pay_to_month_student.month %>.<%= pay_to_month_student.year %></td>
            <td><%= pay_to_month_student.social %></td>
            <td><%= pay_to_month_student.academic %></td>
            <td><%= pay_to_month_student.study %></td>
            <td><%= pay_to_month_student.public %></td>
            <td><%= pay_to_month_student.scientific %></td>
            <td><%= pay_to_month_student.cultural %></td>
            <td><%= pay_to_month_student.sports %></td>

            <td><%=PayToMonthStudent::TYPE_PAY_SHORT[pay_to_month_student.type_pay]%></td>
            <td><%= pay_to_month_student.surcharge %></td>
            <td><%=pay_to_month_student.social.to_i+pay_to_month_student.academic.to_i+pay_to_month_student.study.to_i+pay_to_month_student.public.to_i+pay_to_month_student.scientific.to_i+pay_to_month_student.cultural.to_i+pay_to_month_student.sports.to_i+pay_to_month_student.surcharge.to_i %></td>

            <% if can? :manager, :all%>
                <td bgcolor="#c9302c">
                  <%= link_to 'Show', pay_to_month_student %>
                  <%= link_to 'Edit', edit_pay_to_month_student_path(pay_to_month_student) %>
                  <%= link_to 'Destroy', pay_to_month_student_path(pay_to_month_student), method: :delete, data: { confirm: 'Вы уверены, что хотите удалить?' } %>
                </td>
            <% end %>
        </tr>
    <% end %>
</table>