config/routes.rb
Blog::Application.routes.draw do
  get "students/certificat"
  get "students/pay"


   get "account_to_semesters/pay"
   post "account_to_semesters/pay"

  post "pay_category_to_semesters/new"

  post "pay_category_to_semesters/new1"
  get "pay_category_to_semesters/new1"

  post "pay_category_to_semesters/kalkul"
  get "pay_category_to_semesters/kalkul"

  post "pay_category_to_semesters/stip1"
  get "pay_category_to_semesters/stip1"

  post "pay_category_to_semesters/stip2"
  get "pay_category_to_semesters/stip2"

  get "pay_to_month_students/pay_metod"
  post "pay_to_month_students/pay_metod"


  resources :operations

  resources :students do
    resources :certificats
    resources :student_groups
  end
  resources :groups
  resources :faculties do
    resources :account_to_semesters
  end
  resources :orders


  resources :student_groups
  resources :account_to_semesters

  resources :pay_category_to_semesters
  resources :pay_to_month_students
  resources :certificats
  resources :posts do
    resources :comments
  end
 root "welcome#index"

  get "static_pages/home"

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  #root  'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

  get "new_bases/group"
  get "new_bases/student"
  get "new_bases/student_group"
  post "new_bases/create_student_group"
  post "new_bases/create_student"
  post "new_bases/create_group"
end

app/models/faculty.rb
class Faculty < ActiveRecord::Base
	has_many :account_to_semesters
	has_many :pay_category_to_semesters
	has_many :groups
  has_many :users
  has_many :orders
	validates_uniqueness_of :name,
		message: "Название факультета должно быть уникально" 
	validates_presence_of :name,
		message: "Название факультета должно быть заполнино"
end

app/controllers/faculties_controller.rb
class FacultiesController < ApplicationController
  before_action :signed_in_user
  before_action :correct_faculty

  def new
    @faculty = Faculty.new
  end

  def create
    @faculty = Faculty.new(faculty_params)
    if @faculty.save
      redirect_to @faculty
    else
      render 'new'
    end
  end
  
  def show
    @faculty = Faculty.find(params[:id])
  end

  def index
    @faculties = Faculty.all
  end
  
  def edit
    @faculty = Faculty.find(params[:id])
  end

  def update
    @faculty = Faculty.find(params[:id])
    if @faculty.update(faculty_params)
      redirect_to @faculty
    else
      render 'edit'
    end
  end
  
  def destroy
    @faculty = Faculty.find(params[:id])
    @faculty.destroy
   
    redirect_to faculties_path
  end

private
  def faculty_params
    params.require(:faculty).permit(:name)
  end

  def correct_faculty
    redirect_to help_url, notice: 'Доступ запрещен' unless current_user.faculty.name == 'all'
  end
end

app/helpers/faculties_helper.rb
module FacultiesHelper
  def faculty(controller)
    (current_user.faculty.name == "all") ? controller : controller.find_all { |x| x.faculty_id == current_user.faculty_id }
  end
end

app/views/faculties/edit.html.erb
<h2>Изменение параметров факультета</h2>
 
<%= form_for :faculty, url: faculty_path(@faculty), method: :patch do |f| %>
  <% if @faculty.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@faculty.errors.count, "error") %> prohibited
        this faculty from being saved:</h2>
    <ul>
    <% @faculty.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
   <p>
     Название<br>
    <%= f.text_field :name %>
  </p>


  <p>
    <%= f.submit Сохранить %>
  </p>
<% end %>
 
<%= link_to 'Вернутся к списку', faculties_path %>

app/views/faculties/index.html.erb
<h1>Факультеты</h1>
<%= link_to 'Новый факультет', new_faculty_path %> 


<table class="table table-striped">
  <tr>
      <th>Имя</th>
    <th></th>
    <th>Old_id</th>
  </tr>
 
  <% @faculties.sort_by {|word| word.name}.each do |faculty| %>
    <tr>
		<td><%= faculty.name %></td>
          <td><%= faculty.short_name %></td>
          <td><%= faculty.old_id %></td>
      

     
      <td><%= link_to 'Show', faculty %></td>
	  <td><%= link_to 'Edit', edit_faculty_path(faculty) %></td>
	      <td><%= link_to 'Destroy', faculty_path(faculty),
                    method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>



  <p>
  <a href="/" class="btn btn-large btn-primary enabled">На первую страницу</a>
  </p>

app/views/faculties/new.html.erb
<h2>Создание нового факультета</h2>

<%= form_for :faculty , url: faculties_path do |f| %>
  <% if @faculty.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@faculty.errors.count, "error") %> prohibited
        this faculty from being saved:</h2>
    <ul>
    <% @faculty.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  
   <p>
    Название<br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.submit :Сохранить %>
  </p>
<% end %>

app/views/faculties/show.html.erb
<p>
    <strong>Название факультета:</strong><br>
    <%= @faculty.name %> (<%= @faculty.short_name %>)
</p>

<p>
    <%= link_to 'Изменить факультет', edit_faculty_path(@faculty) %> |
    <%= link_to 'Вернутся к списку', faculties_path %>
</p>