config/routes.rb
Blog::Application.routes.draw do
  get "students/certificat"
  get "students/pay"


   get "account_to_semesters/pay"
   post "account_to_semesters/pay"

  post "pay_category_to_semesters/new"

  post "pay_category_to_semesters/new1"
  get "pay_category_to_semesters/new1"

  post "pay_category_to_semesters/kalkul"
  get "pay_category_to_semesters/kalkul"

  post "pay_category_to_semesters/stip1"
  get "pay_category_to_semesters/stip1"

  post "pay_category_to_semesters/stip2"
  get "pay_category_to_semesters/stip2"

  get "pay_to_month_students/pay_metod"
  post "pay_to_month_students/pay_metod"


  resources :operations

  resources :students do
    resources :certificats
    resources :student_groups
  end
  resources :groups
  resources :faculties do
    resources :account_to_semesters
  end
  resources :orders


  resources :student_groups
  resources :account_to_semesters

  resources :pay_category_to_semesters
  resources :pay_to_month_students
  resources :certificats
  resources :posts do
    resources :comments
  end
 root "welcome#index"

  get "static_pages/home"

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  #root  'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

  get "new_bases/group"
  get "new_bases/student"
  get "new_bases/student_group"
  post "new_bases/create_student_group"
  post "new_bases/create_student"
  post "new_bases/create_group"
end

app/models/account_to_semester.rb
class AccountToSemester < ActiveRecord::Base
	belongs_to :faculty
	has_many :operations
	
	TYPE_ACСOUNT = { 0 => '1курс 1семестр', 1 => 'Повышенная', 2 =>'Социальная+Академическая' , 3=>'Резерв'}
	TYPE_ACСOUNT_SHORT = { 0 => '1к', 1 => 'П', 2 =>'С+А' , 3=>'Р'}
	
	validates_inclusion_of :type_account, in:  TYPE_ACСOUNT.keys,
	message: "Тип счета должен быть заполнин"
	
	# validates_uniqueness_of :type_account, :scope => :faculty_id ,
	# :allow_nil=>true,:allow_blank=>true,
	# message: "Такой счет уже существует"
	
	validates_associated :faculty,message: "Название факультета должно быть заполнино"
	validates_presence_of :faculty_id,
	message: "Название факультета должно быть заполнино"
	
	validates_presence_of :sum,
	message: "Сумма должна быть заполнина"
	
end

app/controllers/account_to_semesters_controller.rb
class AccountToSemestersController < ApplicationController
  before_action :signed_in_user
  before_action :operation, only: [:edit, :update]
  before_action :correct_faculty, only: [:show, :edit, :update, :destroy]

  def new
    @account_to_semester = AccountToSemester.new
  end

  def create
    @account_to_semester = AccountToSemester.new(account_to_semester_params)
    @account_to_semester.faculty_id=current_user.faculty.id
    @account_to_semester.semester=sem_today
    @account_to_semester.year=year_today
    if @account_to_semester.save
      redirect_to @account_to_semester
    else
      render 'new'
    end
  end
  
  def show
    #@account_to_semester = AccountToSemester.find(params[:id])
  end

  def index
    if params[:years].nil? or params[:years].empty?
      @account_to_semesters = faculty(AccountToSemester.includes(:faculty).where(year: year_today))
    else
      @account_to_semesters = faculty(AccountToSemester.includes(:faculty).where(year: params[:years].to_s))
    end
  end

  def edit
    #@account_to_semester = AccountToSemester.find(params[:id])
  end
  
  def update
    #@account_to_semester = AccountToSemester.find(params[:id])
    if @account_to_semester.update(account_to_semester_params)
      redirect_to @account_to_semester
    else
      render 'edit'
    end
  end
  
  def destroy
    #@account_to_semester = AccountToSemester.find(params[:id])
    @account_to_semester.destroy
    redirect_to account_to_semesters_path
  end

private
  def account_to_semester_params
    params.require(:account_to_semester).permit(:type_account, :sum,:faculty_id, :year, :semester)
  end

  def correct_faculty
    @account_to_semester = AccountToSemester.find(params[:id])
    redirect_to help_url, notice: 'Доступ запрещен' unless current_user.faculty.name == 'all' || @account_to_semester.faculty_id == current_user.faculty_id
  end

  def operation
    @account_to_semester = AccountToSemester.find(params[:id])
    redirect_to controller: 'operations', action: 'new', account_to_semester_id: @account_to_semester.id unless current_user.faculty.name == "all"
  end
end

app/helpers/account_to_semesters_helper.rb
module AccountToSemestersHelper
end

app/views/account_to_semesters/edit.html.erb
<h2>Изменение параметров счета на семестр</h2>
 
<%= form_for :account_to_semester, url: account_to_semester_path(@account_to_semester), method: :patch do |f| %>
    <% if @account_to_semester.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(@account_to_semester.errors.count, "error") %> prohibited
            this account_to_semester from being saved:</h2>
            <ul>
                <% @account_to_semester.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    <p>
        Тип счета<br>
        <%= select("account_to_semester", "type_account", AccountToSemester::TYPE_ACСOUNT.map{|k, v| [v, k]}, { include_blank: true })%>
    </p>
    <p>
        Сумма<br>
        <%= f.text_field :sum %>
    </p>

    <div class="form-actions">
        <button type="submit" class="btn btn-success">Сохранить</button>
        <button type="reset" class="btn">Отменить</button>
    </div>
<% end %>

app/views/account_to_semesters/index.html.erb
<h1>Счет на семестр</h1>
<div class="well  well-small">
    <%= form_tag("/account_to_semesters", method: "get") do  %>
        <div class="row">
            <div class="col-md-3">
                <p>
                    Учебный год:<br>
                    <%= select_tag(:years, options_for_select((2013..2023).collect {|p|  "#{p}/#{p+1}" },params[:years] ), { include_blank: true })%>
                </p>
            </div>
            <div class="col-md-1 col-md-offset-7" >
                <button class="btn btn-large btn-info" type="submit" >Поиск</button>
            </div>
        </div>
    <% end %>
</div>
<p>
  <a href="/account_to_semesters/new" class="btn btn-large btn-success enabled">Новый счет на семестр</a>
</p>

<table class="table table-hover">
  <tr>
    <% if can? :manager, :AccountToSemester %>
        <th>Факультет</th>
    <% end %>
    <th>Учебный год</th>
    <th>Семестр</th>
    <th>Тип</th>
    <th>Сумма</th>
    <th></th>
  </tr>

  <% @account_to_semesters.sort_by {|s| [s.faculty_id, s.year, s.semester]}.reverse.each do |account_to_semester| %>
      <tr>
        <% if can? :manager, AccountToSemester %>
            <td><%= account_to_semester.faculty.short_name %></td>
        <% end %>

        <td><%= account_to_semester.year %></td>
        <td><%= account_to_semester.semester %></td>
        <td><%=AccountToSemester::TYPE_ACСOUNT[account_to_semester.type_account]%></td>
        <td><%= link_to "#{account_to_semester.sum}", account_to_semester %></td>

        <% if can? :manager, :all %>
            <td bgcolor="#c9302c">
              <%= link_to 'Show', account_to_semester %>
              <%= link_to 'Edit', edit_account_to_semester_path(account_to_semester) %>
              <%= link_to 'Destroy', account_to_semester_path(account_to_semester), method: :delete, data: { confirm: 'Are you sure?' } %>
            </td>
        <% end %>

        <%if (account_to_semester.year==year_today and account_to_semester.semester==sem_today) or can? :manager, :all %>
            <td><%= link_to 'Изменить', { controller: "operations", action: "new", account_to_semester_id:account_to_semester.id },  :class => "btn btn-primary"  %></td>
        <% else %>
            <td><%= link_to 'Изменить', { controller: "operations", action: "new", account_to_semester_id:account_to_semester.id } , class: "btn btn-primary disabled"%></td>
        <% end %>
      </tr>
  <% end %>
</table>

app/views/account_to_semesters/new.html.erb
<h2>Создание нового счета института</h2>
<%= form_for :account_to_semester , url: account_to_semesters_path do |f| %>
    <% if @account_to_semester.errors.any? %>
        <div id="error_explanation" class="error_explanation">
            <h2>Сообщение: сохранение не удалось из-за <%= @account_to_semester.errors.count %> ошибки:</h2>
            <ul>
                <% @account_to_semester.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    <p>
        Тип счета<br>
        <%= select("account_to_semester", "type_account", AccountToSemester::TYPE_ACСOUNT.map{|k, v| [v, k]}, { include_blank: true })%>
    </p>
    <p>
        Сумма<br>
        <%= f.text_field :sum %>
    </p>

    <div class="form-actions">
        <button type="submit" class="btn btn-success">Сохранить</button>
        <button type="reset" class="btn">Отменить</button>
    </div>
<% end %>

app/views/account_to_semesters/show.html.erb
<p>
  <%= link_to 'Вернутся к списку', account_to_semesters_path,  :class => "btn btn-success"  %>
</p>

<%if can? :manager, :AccountToSemester%>
    <p>
      <strong>Факультет: </strong>
      <%= @account_to_semester.faculty.name %>
    </p>
<% end %>
<p>
  <strong>Тип счета: </strong>
   <%=AccountToSemester::TYPE_ACСOUNT[@account_to_semester.type_account]%>
</p>
<p>
  <strong>Сумма: </strong>
  <%= @account_to_semester.sum %>
</p>

<%if can? :manager, :all%>
    <p>
      <%=  link_to 'Изменить счёт', { controller: 'operations', action: 'new', account_to_semester_id:@account_to_semester.id },  :class => 'btn btn-danger' %>
    </p>
<% end %>

<h3>Операции по счёту:</h3>

<table  class="table table-striped">
    <thead>
        <tr>
            <th>Тип операции</th>
            <th>Сумма </th>
            <th>Дата операции</th>
            <th> Пользователь </th>
            <th> Коментарий </th>
        </tr>
    </thead>

    <tbody>
        <% @account_to_semester.operations.sort_by { |q| q.date_op}.reverse.each do |operation| %>
            <tr>
                <%if operation.type_op==0%>
                  <td>
                    <div class="label label-success">
                      <%= Operation::TYPE_OP[operation.type_op]%>
                    </div>
                  </td>
                <%elsif operation.type_op==1%>
                  <td>
                    <div class="label label-danger">
                      <%= Operation::TYPE_OP[operation.type_op]%>
                    </div>
                  </td>
                <%elsif operation.type_op==2%>
                  <td>
                    <div class="label label-primary">
                      <%= Operation::TYPE_OP[operation.type_op]%>
                    </div>
                  </td>
                <%else%>
                  <td>
                    <div class="label label-inverse">
                      <%= Operation::TYPE_OP[operation.type_op]%>
                    </div>
                  </td>
                <%end%>
                <td><%= operation.sum %></td>
                <td><%=l operation.date_op %></td>
                <td><%= operation.user.name %></td>
                <td><%= operation.text %></td>
            </tr>
        <% end %>
    </tbody>
</table>