config/routes.rb
Blog::Application.routes.draw do
  get "students/certificat"
  get "students/pay"


   get "account_to_semesters/pay"
   post "account_to_semesters/pay"

  post "pay_category_to_semesters/new"

  post "pay_category_to_semesters/new1"
  get "pay_category_to_semesters/new1"

  post "pay_category_to_semesters/kalkul"
  get "pay_category_to_semesters/kalkul"

  post "pay_category_to_semesters/stip1"
  get "pay_category_to_semesters/stip1"

  post "pay_category_to_semesters/stip2"
  get "pay_category_to_semesters/stip2"

  get "pay_to_month_students/pay_metod"
  post "pay_to_month_students/pay_metod"


  resources :operations

  resources :students do
    resources :certificats
    resources :student_groups
  end
  resources :groups
  resources :faculties do
    resources :account_to_semesters
  end
  resources :orders


  resources :student_groups
  resources :account_to_semesters

  resources :pay_category_to_semesters
  resources :pay_to_month_students
  resources :certificats
  resources :posts do
    resources :comments
  end
 root "welcome#index"

  get "static_pages/home"

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  #root  'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

  get "new_bases/group"
  get "new_bases/student"
  get "new_bases/student_group"
  post "new_bases/create_student_group"
  post "new_bases/create_student"
  post "new_bases/create_group"
end

app/models/operation.rb
class Operation < ActiveRecord::Base
	belongs_to :account_to_semester
  belongs_to :user

	TYPE_OP = { 0 => 'приход', 1 => 'расход',2 => 'новая'}
	TYPE_OP_SHORT = { 0 => 'П', 1 => 'Р'}
		
	validates_presence_of :type_op, :date_op, :account_to_semester_id, :sum,
	message: " поле должнобыть заполнено" 
	
	validates_inclusion_of :type_op, in: TYPE_OP.keys,
	message: "Тип операции должен быть заполнин"
	

   validates_acceptance_of  :sum,
	:allow_nil=>false, 
	:if => Proc.new { |a| a.sum<0},
    message: "Сумма должна быть >0" 
end

app/controllers/operations_controller.rb
class OperationsController < ApplicationController
  before_action :signed_in_user
  before_action :correct_faculty, only: [:show, :edit, :update, :destroy]

  def new
    @operation = Operation.new
  end
  
  def create
    @operation = Operation.includes(:account_to_semester).new(operation_params)
    @operation.user_id=current_user.id
    @operation.date_op=Date.today
    @operation.text<<"Предыдущая сумма равна #{@operation.account_to_semester.sum}."
    if @operation.type_op==0
      @operation.account_to_semester.sum+=@operation.sum
    elsif @operation.type_op==1
      @operation.account_to_semester.sum-=@operation.sum
    elsif @operation.type_op==2
      @operation.account_to_semester.sum=@operation.sum
    end
    @operation.account_to_semester.save!
     # raise @operation.inspect
    if @operation.save
     redirect_to @operation.account_to_semester
     else
     render 'new'
	  end
  end
  
  def index
    if current_user.faculty.name=="all"
      @operations = Operation.includes({:account_to_semester=>:faculty},:user)
    else
      @operations = Operation.includes({:account_to_semester=>:faculty},:user).where(faculties:{id: current_user.faculty_id})
    end
  end

  def show
    #@operation = Operation.find(params[:id])
  end

  def edit
    #@operation = Operation.find(params[:id])
  end

  def update
    #@operation = Operation.find(params[:id])
    if @operation.update(operation_params)
      redirect_to @operation
    else
      render action: 'edit'
    end
  end

  def destroy
    #@operation = Operation.find(params[:id])
    @operation.destroy
    redirect_to operations_path
  end

private
  def operation_params
    params.require(:operation).permit(:type_op, :sum, :date_op, :text,:account_to_semester_id)
  end

  def correct_faculty
    @operation = Operation.find(params[:id])
    redirect_to help_url, notice: 'Доступ запрещен' unless current_user.faculty.name == 'all'
  end
end

app/helpers/operations_helper.rb
module OperationsHelper
end

app/views/operations/edit.html.erb
<h2>Изменение параметров счета</h2>

<%= form_for :operation, url: operation_path(@operation), method: :patch do |f| %>
  <% if @operation.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@operation.errors.count, "error") %> prohibited
        this operation from being saved:</h2>
    <ul>
    <% @operation.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

   	<p>
	  Счет:<br>
	  <%= select("operation", "account_to_semester_id", AccountToSemester.all.collect {|p| [ AccountToSemester::TYPE_ACСOUNT[p.type_account]+" ("+p.faculty.name+")", p.id ] }, { include_blank: true })%>
	</p>
     <p>
    Тип операции 
        <%= select("operation", "type_op", Operation::TYPE_OP.map{|k, v| [v, k]}, { include_blank: true })%>
    
</p>
     <p>
    Сумма    <%= f.number_field :sum %>
</p>
     <p>
    Дата операции    <%= f.date_select :date_op %>
</p>
     <p>
    Коментарий    <%= f.text_field :text %>
</p>
     <p>
    <%= f.submit %>
</p>

<% end %>

<%= link_to 'Вернутся к списку', operations_path %>

app/views/operations/index.html.erb
<h1>Операции по счету</h1>

<%if can? :creat, Operation%>
    <p>
        <a href="/operations/new" class="btn btn-large btn-success enabled">Новая операция</a>
    </p>
<%end%>
<table  class="table table-striped">
    <thead>
        <tr>
            <th>Счет</th>
            <th>Тип операции</th>
            <th>Сумма </th>
            <th>Дата операции</th>
            <th> Пользователь </th>
            <th> Коментарий </th>
        </tr>
    </thead>

    <tbody>
        <% @operations.sort_by { |q| q.date_op}.reverse.each do |operation| %>
            <tr>
                <td><%= AccountToSemester::TYPE_ACСOUNT[operation.account_to_semester.type_account]%>(<%= operation.account_to_semester.faculty.short_name%>)</td>
                <%if operation.type_op==0%>
                    <td>
                      <div class="label label-success">
                        <%= Operation::TYPE_OP[operation.type_op]%>
                      </div>
                    </td>
                <%elsif operation.type_op==1%>
                    <td>
                      <div class="label label-danger">
                        <%= Operation::TYPE_OP[operation.type_op]%>
                      </div>
                    </td>
                <%elsif operation.type_op==2%>
                    <td>
                      <div class="label label-primary">
                        <%= Operation::TYPE_OP[operation.type_op]%>
                      </div>
                    </td>
                <%else%>
                    <td>
                      <div class="label label-inverse">
                        <%= Operation::TYPE_OP[operation.type_op]%>
                      </div>
                    </td>
                <%end%>
                <td><%= operation.sum %></td>
                <td><%=l operation.date_op %></td>
                <td><%= operation.user.name %></td>
                <td><%= operation.text %></td>
                <%if can? :manager, :all%>
                    <td bgcolor="#c9302c">
                      <%= link_to 'Show', operation %>
                      <%= link_to 'Edit', edit_operation_path(operation) %>
                      <%= link_to 'Destroy', operation, method: :delete, data: { confirm: 'Are you sure?' } %>
                    </td>
                <%end%>
            </tr>
        <% end %>
    </tbody>
</table>





   

app/views/operations/new.html.erb
<h2>Создание новой операции</h2>

<%= form_for :operation , url: operations_path do |f| %>
    <% if @operation.errors.any? %>
    <div id="error_explanation">
        <h2><%= pluralize(@operation.errors.count, "error") %> prohibited this operation from being saved:</h2>
        <ul>
            <% @operation.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
    <% end %>
    <p>
        <!--Счет -->
        <%= f.hidden_field :account_to_semester_id, value: params[:account_to_semester_id] %>
    </p>
    <p>
        Тип операции
        <%= select("operation", "type_op", Operation::TYPE_OP.map{|k, v| [v, k]}, { include_blank: true })%>
    </p>
    <p>
        Сумма
        <%= f.number_field :sum %>
    </p>
    <p>
        <!--Дата операции -->
        <% f.date_select :date_op %>
    </p>
    <p>
        Комментарий  <br>
        <%= f.text_area :text %>
    </p>
    <div class="form-actions">
        <button type="submit" class="btn btn-success">Сохранить</button>
        <button type="reset" class="btn">Отменить</button>
    </div>
<% end %>

app/views/operations/show.html.erb
<p>
  <strong>Тип операции:</strong>
  <%= @operation.type_op %>
</p>

<p>
  <strong>Сумма:</strong>
  <%= @operation.sum %>
</p>

<p>
  <strong>Дата операции:</strong>
  <%=l @operation.date_op %>
</p>

<p>
  <strong>Комментарий:</strong>
  <%= @operation.text %>
</p>


<p>
    <a href="/operations" class="btn btn-large btn-primary enabled">Вернутся к списку</a>
</p>